# Generated by Django 4.2 on 2023-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('P', 'En proceso'), ('A', 'Arreglada'), ('PR', 'Pendiente de revisión'), ('D', 'Descartada')], default=0, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('author', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
    ]
