# Generated by Django 4.1.7 on 2023-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('P', 'En proceso'), ('A', 'Arreglado')], default=0, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
    ]
