# Generated by Django 4.2 on 2023-05-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20230510_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaPorNotificar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia por notificar',
                'verbose_name_plural': 'Incidencias por notificar',
            },
        ),
    ]
